<?php require 'templates/layout/header.phtml' ?>

<?php $userModel = new UserModel(); ?>


<h2>Listado de Libros</h2>
<ul>
    <?php foreach($books as $book): ?>
        <li> <a href="<?php echo BASE_URL . 'book/' . $book->id ?>"> <?php echo $book->nombre ?> </a> </li>
    <?php endforeach ?>
</ul>

<?php if(isset($_SESSION['ID_USER']) && $userModel->isAdmin($_SESSION['ID_USER'])): ?>
    <form method="post" action="<?php echo BASE_URL . 'editGenre/' . $genre->id ?>">
    <div class="form-grup">
        <label for="nombre">Nombre del Género</label>
        <input type="text" class="form-control" id="nombre" name="nombre" required>
    </div>
    <button type="submit" class="btn btn-primary">Editar</button>
</form>
<?php endif ?>


<?php require 'templates/layout/footer.phtml' ?>