<?php require_once 'app/models/user.model.php' ?>
<?php require 'templates/layout/header.phtml' ?>

<?php $userModel = new UserModel(); ?>

<h2>Listado de Libros</h2>
<ul>
    <?php foreach($catalogue as $book): ?>
        <li> <a href="book/<?php echo $book->id ?>"> <?php echo $book->nombre ?> </a> </li>
        <?php if(isset($_SESSION['ID_USER']) && $userModel->isAdmin($_SESSION['ID_USER'])): ?>
            <a href="delete/<?php echo $book->id ?>" class="btn btn-outline-danger">Eliminar</a>

        <?php endif ?>
    <?php endforeach ?>
</ul>
    
<?php if(isset($_SESSION['ID_USER']) && $userModel->isAdmin($_SESSION['ID_USER'])): ?>
    <button> <a href="showAddBook/">Agregar</a> </button>
<?php endif ?>

<h2>Listado de Géneros</h2>
<ul>
    <?php foreach($genres as $genre): ?>
        <li> <a href="genre/<?php echo $genre->id ?>"> <?php echo $genre->nombre ?> </a> </li>
    <?php endforeach ?>
</ul>

<?php require 'templates/layout/footer.phtml' ?>
