<?php require 'templates/layout/header.phtml' ?>


<form method="post" action="add">
    <div class="form-grup">
        <label for="nombre">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" required>
    </div>
    <div class="form-grup">
        <label for="autor">Autor</label>
        <input type="text" class="form-control" id="autor" name="autor" required>
    </div>
    <div class="form-grup">
        <label for="editorial">Editorial</label>
        <input type="text" class="form-control" id="editorial" name="editorial" required>
    </div>
    <div class="form-grup">
        <label for="genero">Genero</label>
        <input type="text" class="form-control" id="genero" name="genero" required>
    </div>    
    <div class="form-grup">
        <label for="stock">stock</label>
        <input type="number" class="form-control" id="stock" name="stock" required>
    </div>
    <button type="submit" class="btn btn-primary">Añadir</button>
</form>



<?php require 'templates/layout/footer.phtml' ?>