<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class="alert alert-danger" role="alert">
        <?= $error ?>
    </div>
<?php endif ?>
<form method="post" action="login">
    <div class="form-grup">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="form-grup">
        <label for="contraseña">Password</label>
        <input type="password" class="form-control" id="contraseña" name="contraseña" required>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>



<?php require 'templates/layout/footer.phtml' ?>