<?php require 'templates/layout/header.phtml' ?>


<form method="post" action="register">
    <div class="form-grup">
        <label for="nombre">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" required>
    </div>
    <div class="form-grup">
        <label for="apellido">Apellido</label>
        <input type="text" class="form-control" id="apellido" name="apellido" required>
    </div>
    <div class="form-grup">
        <label for="dni">DNI</label>
        <input type="number" class="form-control" id="dni" name="dni" required>
    </div>
    <div class="form-grup">
        <label for="telefono">Telefono</label>
        <input type="number" class="form-control" id="telefono" name="telefono" required>
    </div>    
    <div class="form-grup">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="form-grup">
        <label for="contraseña">Password</label>
        <input type="password" class="form-control" id="contraseña" name="contraseña" required>
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
</form>



<?php require 'templates/layout/footer.phtml' ?>